ktor:
  application:
    modules:
      - org.delcom.ApplicationKt.module

  deployment:
    port: 8000
    host: localhost

  database:
    host: 127.0.0.1
    port: 5432
    name: db_pam_p5
    user: postgres
    password: postgres

  jwt:
    secret: mysecret123